name: auto-merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "CI"

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto-Merge"
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: dependabot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
