name: auto-merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "CI"

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto-Merge"
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.mytoken }}
